#ifndef __ETL_PROFILE_H__
#define __ETL_PROFILE_H__

#define ETL_COMPILER_GENERIC
#define ETL_CPP11_SUPPORTED 1
#define ETL_CPP14_SUPPORTED 1
#define ETL_CPP17_SUPPORTED 1
#define ETL_NO_CPP_NAN_SUPPORT
#define ETL_NO_NULLPTR_SUPPORT 0
#define ETL_NO_LARGE_CHAR_SUPPORT 0
#define ETL_CPP11_TYPE_TRAITS_IS_TRIVIAL_SUPPORTED 0
#define ETL_NO_STL
#define ETL_COMPILER_GCC 1

#ifdef _POSIX
#else
    #define ETL_NO_64BIT_TYPES
    #define ETL_TARGET_OS_FREERTOS
#endif

#endif /* CONF_ETL_H_ */