#include "logger.h"

void a_c_function_with_a_very_long_name()
{
   LOG_DEBUG("a_very_long_domain_name",
         "Heureux qui, comme Ulysse, a fait un beau voyage,\n"
         "Ou comme cestuy-la qui conquit la toison,\n"
         "Et puis est retourne, plein d'usage et raison,\n"
         "Vivre entre ses parents le reste de son age !\n"
         "\n"
         "Quand reverrai-je, helas, de mon petit village\n"
         "Fumer la cheminee, et en quelle saison\n"
         "Reverrai-je le clos de ma pauvre maison,\n"
         "Qui m'est une province, et beaucoup davantage ?\n"
         "\n"
         "Plus me plait le sejour qu'ont bati mes aieux,\n"
         "Que des palais Romains le front audacieux,\n"
         "Plus que le marbre dur me plait l'ardoise fine :\n"
         "\n"
         "Plus mon Loir gaulois, que le Tibre latin,\n"
         "Plus mon petit Lire, que le mont Palatin,\n"
         "Et plus que l'air marin la doulceur angevine.\n"
         "Heureux qui, comme Ulysse, a fait un beau voyage,\n"
         "Ou comme cestuy-la qui conquit la toison,\n"
         "Et puis est retourne, plein d'usage et raison,\n"
         "Vivre entre ses parents le reste de son age !\n"
         "\n"
         "Quand reverrai-je, helas, de mon petit village\n"
         "Fumer la cheminee, et en quelle saison\n"
         "Reverrai-je le clos de ma pauvre maison,\n"
         "Qui m'est une province, et beaucoup davantage ?\n"
         "\n"
         "Plus me plait le sejour qu'ont bati mes aieux,\n"
         "Que des palais Romains le front audacieux,\n"
         "Plus que le marbre dur me plait l'ardoise fine :\n"
         "\n"
         "Plus mon Loir gaulois, que le Tibre latin,\n"
         "Plus mon petit Lire, que le mont Palatin,\n"
         "Et plus que l'air marin la doulceur angevine.\n"
         "Heureux qui, comme Ulysse, a fait un beau voyage,\n"
         "Ou comme cestuy-la qui conquit la toison,\n"
         "Et puis est retourne, plein d'usage et raison,\n"
         "Vivre entre ses parents le reste de son age !\n"
         "\n"
         "Quand reverrai-je, helas, de mon petit village\n"
         "Fumer la cheminee, et en quelle saison\n"
         "Reverrai-je le clos de ma pauvre maison,\n"
         "Qui m'est une province, et beaucoup davantage ?\n"
         "\n"
         "Plus me plait le sejour qu'ont bati mes aieux,\n"
         "Que des palais Romains le front audacieux,\n"
         "Plus que le marbre dur me plait l'ardoise fine :\n"
         "\n"
         "Plus mon Loir gaulois, que le Tibre latin,\n"
         "Plus mon petit Lire, que le mont Palatin,\n"
         "Et plus que l'air marin la doulceur angevine.\n"
   );
}
